### PR TITLE
require sudo

### PR DESCRIPTION
**Pull request by wibeasley**

### CODE REVIEW

**Comment by stevepeak** [comment]
Thanks for the PR. Is sudo required for all R projects?

**Comment by wibeasley** [comment]
sudo is required for now, at least.  As I understand it, the reason involves setting up the host to build the package, and not about the R package itself.

If you want more details, these are most of the guys who set the precedent (that most of the R community follows for CI practices).
- [Native R support in Travis and containers](https://github.com/craigcitro/r-travis/issues/154)
- [sudo error during travis check](https://github.com/craigcitro/r-travis/issues/151)

**Comment by stevepeak** [comment]
Cool! Thanks you!

**Comment by wibeasley** [comment]
No problem.  

By the way, I love your implementation of displaying the longitudinal coverage rate in a short fat hosted svg ([for example](https://codecov.io/github/IALSA/IalsaSynthesis/features/graph)).  It reminds of Tufte's sparklines that some of the financial publications picked up ~8 years ago, where the little graphs are mixed in on the same line as the rest of the text, instead of requiring a huge offset graph.

**Comment by stevepeak** [comment]
Thanks :) I appreciate the feedback :+1:

**Pull request merged**
